
export default {
    watch: {
        formData:{
            handler(newVal,oldVal) {
                this.handleAgreement(newVal);
            },
            deep: true
        },
        'formData.item_id'(newVal){
            this.getSelectItems(newVal)
        },
        'formData.mot_id'(newVal){
            this.getSelectMots(newVal)
            
            this.getMotslist(newVal);
        },
        'formData.project_facilitator_id'(newVal){
            this.getUsers(newVal)
        },
        'formData.carrier_supporter_id'(newVal){
            this.getCarrierUsers(newVal)
        },
        'formData.company_id'(newVal){
            this.getSettleComs(newVal)
        },
        'formData.transfer_total'(){
            this.handleCompanyEarnings();
        },
        'formData.tax'(){
            this.handleCompanyEarnings();
            this.getDealApproval()
        },
        'formData.tax_unit'(){
            this.handleCompanyEarnings();
            this.getDealApproval()
        },
        'formData.investment_assets'(){
            this.handleCompanyEarnings();
        },
        'formData.investment_assets_unit'(){
            this.handleCompanyEarnings();
        },
        'formData.transfer_price'(){
            this.handleCompanyEarnings();
        },
        'formData.transfer_total'(){
            this.handleCompanyEarnings();
        },
        'formData.transfer_total_unit'(){
            this.handleCompanyEarnings();
        },
        'formData.land_cost'(){
            this.handleCompanyEarnings();
        },
        'formData.assets_cost'(){
            this.handleCompanyEarnings();
        },
        'formData.tax_cost'(){
            this.handleCompanyEarnings();
        },
        'formData.other_cost'(){
            this.handleCompanyEarnings();
        },
        'formData.other_cost_unit'(){
            this.handleCompanyEarnings();
        },
        'formData.estimated_revenue_unit'(){
            this.handleCompanyEarnings();
        },
     }
}
